### ISSUE TITLE
Doesn't work on Arch Linux: IndexError: bpy_prop_collection[index]: index 3 out of range, size 3

### ISSUE THREAD

**Issue by juozasmiskinis** [beautiful-atoms/beautiful-atoms#209]
**Describe the bug**
This error comes up when trying to display some object using GUI or Python.
```bash
Python: Traceback (most recent call last):
  File "/home/user/.config/blender/4.1/scripts/addons/batoms/ops/add_object.py", line 129, in execute
    batoms = Batoms(label=self.label, from_ase=atoms)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.config/blender/4.1/scripts/addons/batoms/batoms.py", line 156, in __init__
    self._cell = Bcell(label, cell, batoms=self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.config/blender/4.1/scripts/addons/batoms/cell.py", line 28, in __init__
    self.build_object(array, location)
  File "/home/user/.config/blender/4.1/scripts/addons/batoms/cell.py", line 69, in build_object
    self.build_geometry_node()
  File "/home/user/.config/blender/4.1/scripts/addons/batoms/cell.py", line 100, in build_geometry_node
    links.new(PositionCell.outputs["Position"], TransferCell.inputs[3])
                                                ~~~~~~~~~~~~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 3 out of range, size 3
```

**To Reproduce**
1. Install on Arch Linux using the [manual installation method](https://beautiful-atoms.readthedocs.io/en/latest/getting_started/installing/linux.html).
2. In `Object mode`, click `Add -> Batoms -> Atoms`. The error appears.

Alternatively, in the Python terminal:
1. Define the H2O molecule as suggested in the `Usage` section:
```python
from batoms import Batoms
h2o = Batoms("h2o",
            species = ["O", "H", "H"],
            positions= [[0, 0, 0], [0, -0.76, -0.6], [0, 0.76, -0.6]])
```
2. The error appears after the attempt to define `h2o`.

**Expected behavior**
There should be no errors.

**Desktop:**
OS: Arch Linux 6.8.7-arch1-1

**Blender Version**
4.1.1

**Additional context**
AFAIK, there is no such thing as `Blender’s bundled python location` on Arch Linux, therefore I can't use `install.py`.

**Comment by liuyun88** [comment]
I can reproduce this error on Blender 4.1.1 on Windows 11

**Comment by superstar54** [comment]
Hi @juozasmiskinis and @liuyun88 , thanks for reporting this issue. I can also reproduce this error. There seems an update of Python API in Blender 4.1.1. I will fix this issue asap.

**Comment by superstar54** [comment]
Hi All, indeed, Blender 4.1 refactors the sockets of many nodes. I suggest you use **Blender 4.0** for the moment. 
I will update you when I fix this issue.

**Comment by juozasmiskinis** [comment]
Thanks for the heads up!

**Comment by liuyun88** [comment]
Just wondering if this has been fixed. Using the blender4.1 branch still gives the following error

`Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "<string>", line 19, in <module>
  File "/usr/share/blender/4.1/scripts/addons/batoms/batoms.py", line 156, in __init__
    self._cell = Bcell(label, cell, batoms=self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/batoms/cell.py", line 28, in __init__
    self.build_object(array, location)
  File "/usr/share/blender/4.1/scripts/addons/batoms/cell.py", line 69, in build_object
    self.build_geometry_node()
  File "/usr/share/blender/4.1/scripts/addons/batoms/cell.py", line 157, in build_geometry_node
    input_nodes[faces[i][j]].outputs["Value"],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Value" not found'`
