### ISSUE TITLE
The bug of input

### ISSUE THREAD

**Issue by hanjiahe1999** [beautiful-atoms/beautiful-atoms#230]
**Describe the bug**
When i want to test the first example of batoms, something is wrong.

some informations

`Python: Traceback (most recent call last):
  File "/opt/blender-4.2.0-linux-x64/4.2/scripts/addons_core/batoms/ops/add_object.py", line 34, in execute
    batoms = Batoms(label=self.label, from_ase=atoms)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/blender-4.2.0-linux-x64/4.2/scripts/addons_core/batoms/batoms.py", line 156, in __init__
    self._cell = Bcell(label, cell, batoms=self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/blender-4.2.0-linux-x64/4.2/scripts/addons_core/batoms/cell.py", line 28, in __init__
    self.build_object(array, location)
  File "/opt/blender-4.2.0-linux-x64/4.2/scripts/addons_core/batoms/cell.py", line 69, in build_object
    self.build_geometry_node()
  File "/opt/blender-4.2.0-linux-x64/4.2/scripts/addons_core/batoms/cell.py", line 100, in build_geometry_node
    links.new(PositionCell.outputs["Position"], TransferCell.inputs[3])
                                                ~~~~~~~~~~~~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 3 out of range, size 3`

**Desktop:**
 - OS: Linux

**Blender Version**
- 4.2.0

**Comment by superstar54** [comment]
HI @hanjiahe1999 , thanks for reporting the issue.
Please see #https://github.com/beautiful-atoms/beautiful-atoms/issues/209. I suggest you use Blender 4.0 for the moment.

@alchem0x2A  and I  are working on this #220.
